spring.application.name=evaluacion-docente


spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:evaluador_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:root}

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10

# Flyway
spring.flyway.enabled=true
# Directorio donde Flyway buscará los scripts de migración SQL
spring.flyway.locations=classpath:db/migration
# Permite migrar una base de datos existente sin historial previo (útil si ya tienes tablas), osea que si ya estabas trabjando sin flyway y despues integras flyway,
#se  permitira que flyway haga las migraciones a partir de ese punto
spring.flyway.baseline-on-migrate=true
# Valida que las migraciones sean consistentes antes de migrar (RECOMENDADO en producción)
spring.flyway.validate-on-migrate=true

#No usar en produccion, comentarlas
# Permite limpiar la base de datos (eliminar todas las tablas) usando Flyway (solo para desarrollo), no apto para produccion
#spring.flyway.clean-disabled=false
# Si ocurre un error de validación, Flyway limpiará la base de datos automáticamente antes de migrar, no apto para produccion
#spring.flyway.clean-on-validation-error=true

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs

# JWT secret (cambiar en producción)
app.jwt.secret=secret-key-por-defecto-cambiar
