spring.application.name=evaluacion-docente


spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:evaluador_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:root}

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs

# JWT secret (cambiar en producción)
app.jwt.secret=secret-key-por-defecto-cambiar
